# Generated by Django 5.2.13 on 2026-05-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('usia', models.PositiveIntegerField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('hasil', models.CharField(choices=[('normal', 'Normal'), ('protanopia', 'Protanopia'), ('deuteranopia', 'Deuteranopia'), ('tritanopia', 'Tritanopia'), ('total', 'Buta Warna Total')], default='normal', max_length=20)),
                ('skor', models.IntegerField(default=0)),
                ('total_soal', models.IntegerField(default=5)),
                ('tanggal_tes', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hasil Tes',
                'verbose_name_plural': 'Hasil Tes',
                'ordering': ['-tanggal_tes'],
            },
        ),
    ]
